import type { Metadata } from "next";
import "./globals.css";
import {
  SidebarHeader,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/mode-toggle";
import { IoFlash } from "react-icons/io5";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      {" "}
      <body>
        {" "}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {" "}
          <SidebarProvider>
            {" "}
            <div className="flex min-h-screen w-full">
              {" "}
              {/* Sidebar tetap di kiri */} <AppSidebar /> {/* Area konten */}{" "}
              <div className="flex flex-col flex-1">
                {" "}
                {/* Header */}{" "}
                <header className="flex items-center justify-between p-4 border-b">
                  {" "}
                  <SidebarTrigger />{" "}
                  <SidebarHeader className="text-lg flex flex-row items-center">
                    <IoFlash className="text-yellow-400" />
                    Ekstrama Mitra Mandiri
                    <IoFlash className="text-yellow-400" />
                  </SidebarHeader>{" "}
                  <ModeToggle />{" "}
                </header>{" "}
                {/* Main content */}{" "}
                <main className="flex-1 p-4">{children}</main>{" "}
              </div>{" "}
            </div>{" "}
          </SidebarProvider>{" "}
        </ThemeProvider>{" "}
      </body>{" "}
    </html>
  );
}
